version: 2

references:
  python_node_image: &python_node_image
    docker:
      - image: circleci/python:3.6.5-node

  node_image: &node_image
    docker:
      - image: circleci/node:10

  go_image: &go_image
    working_directory: /go/src/github.com/govau/notify
    docker:
      - image: circleci/golang:1.10

  deploy_image: &deploy_image
    docker:
      - image: circleci/python:3.6.5-node

  undeploy_image: &undeploy_image
    docker:
      - image: circleci/python:3.7-node

  attach_workspace: &attach_workspace
    attach_workspace:
      at: .

  cf_install: &cf_install
    run:
      command: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
        mkdir -p `pwd`/bin
        chmod +x ./cf
        mv ./cf bin/
        echo export PATH="$PWD/bin:\$PATH" >> $BASH_ENV
        source $BASH_ENV
        cf install-plugin -f https://github.com/contraband/autopilot/releases/download/0.0.6/autopilot-linux

  cf_login: &cf_login
    run:
      command: make cf-login

  cf_login_prod: &cf_login_prod
    run:
      command: make cf-login-prod

  master_branch: &master_branch
    filters:
      branches:
        only:
          - master

  not_master_branch: &not_master_branch
    filters:
      branches:
        ignore:
          - master

jobs:
  setup:
    <<: *python_node_image
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - Makefile
            - utils
            - proto
            - api
            - graphql-api
            - rpc-api
            - admin
            - status
            - ci

  build-admin:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make admin.setup
      - run: make admin.build
      - persist_to_workspace:
          root: .
          paths:
            - admin

  test-admin:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make admin.setup-dev
      - run: echo 're-enable tests here'
      - run: echo 'make admin.test'

  test-api:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make api.setup-dev
      - run: echo 're-enable tests here'
      - run: echo 'make api.test'

  build-api:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make api.setup
      - run: make api.build
      - persist_to_workspace:
          root: .
          paths:
            - api

  build-graphql-api:
    <<: *node_image
    steps:
      - *attach_workspace
      - run: make graphql-api.setup
      - run: make graphql-api.build
      - persist_to_workspace:
          root: .
          paths:
            - graphql-api

  build-rpc-api:
    <<: *go_image
    steps:
      - *attach_workspace
      - run: make rpc-api.setup
      - run: make rpc-api.build
      - persist_to_workspace:
          root: .
          paths:
            - rpc-api

  cleanup-old-deploys:
    <<: *undeploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make -C ci undeploy-feature-branches

  deploy-dev-admin:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make admin.deploy-dev

  deploy-dev-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make create-service-psql
      - run: make api.deploy-dev

  deploy-dev-celery:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make create-service-psql
      - run: make api.deploy-dev-celery

  deploy-dev-graphql-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make graphql-api.deploy-dev

  deploy-dev-rpc-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make rpc-api.deploy-dev

  deploy-prod-admin:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make admin.deploy

  deploy-prod-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make api.deploy

  deploy-prod-celery:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make api.deploy-celery

  deploy-prod-graphql-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make graphql-api.deploy

  deploy-prod-rpc-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make rpc-api.deploy

  deploy-statuspage:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make status.deploy


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup
      - build-admin:
          requires:
            - setup

      - build-api:
          requires:
            - setup

      - build-graphql-api:
          requires:
            - setup

      - build-rpc-api:
          requires:
            - setup

      - test-admin:
          requires:
            - setup

      - test-api:
          requires:
            - setup

      - deploy-dev-admin:
          requires:
            - build-admin
            - test-admin

      - deploy-dev-api:
          requires:
            - build-api
            - test-api

      - deploy-dev-graphql-api:
          requires:
            - build-graphql-api

      - deploy-dev-rpc-api:
          requires:
            - build-rpc-api

      - deploy-dev-celery:
          requires:
            - build-api
            - test-api

      - cleanup-old-deploys:
          requires:
            - setup

      - unlock-prod-deploy:
          <<: *master_branch
          type: approval
          requires:
            - deploy-dev-admin
            - deploy-dev-api
            - deploy-dev-celery

      - deploy-prod-admin:
          <<: *master_branch
          requires:
            - unlock-prod-deploy

      - deploy-prod-api:
          <<: *master_branch
          requires:
            - unlock-prod-deploy

      - deploy-prod-celery:
          <<: *master_branch
          requires:
            - unlock-prod-deploy

      - deploy-statuspage:
          <<: *master_branch
          requires:
            - unlock-prod-deploy
