version: 2

references:
  python_node_image: &python_node_image
    docker:
      - image: circleci/python:3.6.5-node

  deploy_image: &deploy_image
    docker:
      - image: circleci/python:3.6.5-node

  attach_workspace: &attach_workspace
    attach_workspace:
      at: .

  cf_install: &cf_install
    run:
      command: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
        mkdir -p `pwd`/bin
        chmod +x ./cf
        mv ./cf bin/
        echo export PATH="$PWD/bin:\$PATH" >> $BASH_ENV
        source $BASH_ENV
        cf install-plugin -f https://github.com/contraband/autopilot/releases/download/0.0.6/autopilot-linux

  cf_login: &cf_login
    run:
      command: make cf-login

  cf_login_prod: &cf_login_prod
    run:
      command: make cf-login-prod

  master_branch: &master_branch
    filters:
      branches:
        only:
          - master

  not_master_branch: &not_master_branch
    filters:
      branches:
        ignore:
          - master

jobs:
  setup:
    <<: *python_node_image
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - Makefile
            - utils
            - api
            - admin

  build-admin:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make -C admin setup
      - run: make -C admin vendor
      - persist_to_workspace:
          root: .
          paths:
            - admin

  test-admin:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make -C admin setup-dev
      - run: echo 're-enable tests here'
      - run: echo 'make -C admin test'

  test-api:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make -C api setup-dev
      - run: echo 're-enable tests here'
      - run: echo 'make -C api test'

  build-api:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make -C api setup
      - run: make -C api vendor
      - persist_to_workspace:
          root: .
          paths:
            - api

  deploy-dev-admin:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make -C admin deploy-dev

  deploy-dev-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make -C api deploy-dev

  deploy-dev-celery:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make -C api deploy-dev-celery

  deploy-prod-admin:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make -C admin deploy

  deploy-prod-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make -C api deploy

  deploy-prod-celery:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make -C api deploy-celery


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup
      - build-admin:
          requires:
            - setup

      - build-api:
          requires:
            - setup

      - test-admin:
          requires:
            - setup

      - test-api:
          requires:
            - setup

      - deploy-dev-admin:
          requires:
            - build-admin
            - test-admin

      - deploy-dev-api:
          requires:
            - build-api
            - test-api

      - deploy-dev-celery:
          requires:
            - build-api
            - test-api

      - unlock-prod-deploy:
          <<: *master_branch
          type: approval
          requires:
            - deploy-dev-admin
            - deploy-dev-api
            - deploy-dev-celery

      - deploy-prod-admin:
          <<: *master_branch
          requires:
            - unlock-prod-deploy

      - deploy-prod-api:
          <<: *master_branch
          requires:
            - unlock-prod-deploy

      - deploy-prod-celery:
          <<: *master_branch
          requires:
            - unlock-prod-deploy
