version: 2

references:
  python_node_image: &python_node_image
    docker:
      - image: circleci/python:3.6.5-node

  python_node_postgres_images: &python_node_postgres_images
    docker:
      - image: circleci/python:3.6.5-node
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_notification_api

  deploy_image: &deploy_image
    docker:
      - image: circleci/python:3.6.5-node

  undeploy_image: &undeploy_image
    docker:
      - image: circleci/python:3.7-node

  attach_workspace: &attach_workspace
    attach_workspace:
      at: .

  cf_install: &cf_install
    run:
      command: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
        mkdir -p `pwd`/bin
        chmod +x ./cf
        mv ./cf bin/
        echo export PATH="$PWD/bin:\$PATH" >> $BASH_ENV
        source $BASH_ENV
        cf install-plugin -f https://github.com/contraband/autopilot/releases/download/0.0.6/autopilot-linux

  cf_login: &cf_login
    run:
      command: make cf-login

  cf_login_prod: &cf_login_prod
    run:
      command: make cf-login-prod

  master_branch: &master_branch
    filters:
      branches:
        only:
          - master

  not_master_branch: &not_master_branch
    filters:
      branches:
        ignore:
          - master

  api_tests_environment: &api_tests_environment
    environment:
      TEST_PIPENV_DOTENV_LOCATION: ""
      FLASK_APP: "application.py"
      NOTIFY_ENVIRONMENT: "test"
      TWILIO_ACCOUNT_SID: "twilio-account-sid"
      TWILIO_AUTH_TOKEN: "twilio-auth-token"

jobs:
  setup:
    <<: *python_node_image
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - Makefile
            - utils
            - api
            - admin
            - status
            - ci

  build-admin:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make admin.setup
      - run: make admin.vendor
      - persist_to_workspace:
          root: .
          paths:
            - admin

  test-admin:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make admin.setup-dev
      - run: echo 're-enable tests here'
      - run: echo 'make admin.test'

  test-api:
    <<: *python_node_postgres_images
    steps:
      - *attach_workspace
      - run: make api.setup-dev
      - run:
          name: Wait for Postgres to be ready
          environment:
            DOCKER_TEST_DB_PORT: "5432"
          command: |
            make -C api wait-for-docker-test-db
      # - run:
      #     name: test-accept_invite
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-accept_invite
      # - run:
      #     name: test-authentication
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-authentication
      # - run:
      #     name: test-aws
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-aws
      # - run:
      #     name: test-commands
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-commands
      # - run:
      #     name: test-dvla_organisation
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-dvla_organisation
      # - run:
      #     name: test-email_branding
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-email_branding
      # - run:
      #     name: test-events
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-events
      # - run:
      #     name: test-inbound_number
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-inbound_number
      # - run:
      #     name: test-inbound_sms
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-inbound_sms
      # - run:
      #     name: test-invite
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-invite
      # - run:
      #     name: test-job
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-job
      # - run:
      #     name: test-notifications
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-notifications
      # - run:
      #     name: test-organisation
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-organisation
      # - run:
      #     name: test-roots
      #     <<: *api_tests_environment
      #     command: |
      #       make -C api test-roots
      - run:
          name: test-status
          <<: *api_tests_environment
          command: |
            make -C api test-status

  build-api:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make api.setup
      - run: make api.vendor
      - persist_to_workspace:
          root: .
          paths:
            - api

  cleanup-old-deploys:
    <<: *undeploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make -C ci undeploy-feature-branches

  deploy-dev-admin:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make admin.deploy-dev

  deploy-dev-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make create-service-psql
      - run: make api.deploy-dev

  deploy-dev-celery:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make create-service-psql
      - run: make api.deploy-dev-celery

  deploy-prod-admin:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make admin.deploy

  deploy-prod-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make api.deploy

  deploy-prod-celery:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make api.deploy-celery

  deploy-statuspage:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make status.deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup
      - build-admin:
          requires:
            - setup

      # - build-api:
      #     requires:
      #       - setup

      # - test-admin:
      #     requires:
      #       - setup

      - test-api:
          requires:
            - setup

      # - deploy-dev-admin:
      #     requires:
      #       - build-admin
      #       - test-admin

      # - deploy-dev-api:
      #     requires:
      #       - build-api
      #       - test-api

      # - deploy-dev-celery:
      #     requires:
      #       - build-api
      #       - test-api

      # - cleanup-old-deploys:
      #     requires:
      #       - setup

      # - unlock-prod-deploy:
      #     <<: *master_branch
      #     type: approval
      #     requires:
      #       - deploy-dev-admin
      #       - deploy-dev-api
      #       - deploy-dev-celery

      # - deploy-prod-admin:
      #     <<: *master_branch
      #     requires:
      #       - unlock-prod-deploy

      # - deploy-prod-api:
      #     <<: *master_branch
      #     requires:
      #       - unlock-prod-deploy

      # - deploy-prod-celery:
      #     <<: *master_branch
      #     requires:
      #       - unlock-prod-deploy

      # - deploy-statuspage:
      #     <<: *master_branch
      #     requires:
      #       - unlock-prod-deploy
